#!/usr/bin/env python3
"""Generates tests/xd_fixtures.h - the committed CrossDevice proof fixtures.

The cross-device hash proof (plan 19.4) runs on committed bank BYTES, never on
re-baked content (T-057 N2): every runner scores exactly these int8 rows, these
float-bit scales, and these float-bit queries, so cross-device evidence is
bit-identical by git. The adversarial banks (T-057 S1) engineer row-scale x
query-scale products into and around the float subnormal window, so the hash
arbiter rules on the FTZ/DAZ weak case rather than around it.

Regeneration is an intentional, recorded event: it changes the golden hash and
must be re-pinned deliberately.
"""

import struct
import sys

SEED = 0x5EEDC0DE


class Rng:
    """xorshift64* - matches no in-repo RNG on purpose; fixture bytes are what ship."""

    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFFFFFFFFFF or 1

    def next(self):
        s = self.s
        s ^= (s >> 12) & 0xFFFFFFFFFFFFFFFF
        s = (s ^ (s << 25)) & 0xFFFFFFFFFFFFFFFF
        s ^= s >> 27
        self.s = s
        return (s * 0x2545F4914F6CDD1D) & 0xFFFFFFFFFFFFFFFF

    def i8(self):
        # Full int8 kernel range [-127, 127].
        return (self.next() % 255) - 127

    def unit(self):
        return (self.next() >> 11) / float(1 << 53)  # [0, 1)


def f32_bits(x):
    return struct.unpack("<I", struct.pack("<f", x))[0]


def make_bank(rng, count, dims, scale_fn):
    rows = [[rng.i8() for _ in range(dims)] for _ in range(count)]
    scales = [scale_fn(r, rng) for r in range(count)]
    return rows, scales


def emit_i8(name, rows):
    flat = [v for row in rows for v in row]
    lines = [f"alignas(16) static const int8_t {name}[{len(flat)}] = {{"]
    for i in range(0, len(flat), 20):
        lines.append("\t" + ", ".join(str(v) for v in flat[i:i + 20]) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_u32(name, vals):
    lines = [f"static const uint32_t {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), 8):
        lines.append("\t" + ", ".join(f"0x{v:08x}u" for v in vals[i:i + 8]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    golden = int(sys.argv[1], 16) if len(sys.argv) > 1 else 0
    rng = Rng(SEED)
    out = []
    out.append("// Generated by tools/gen_xd_fixtures.py - committed CrossDevice proof")
    out.append("// fixtures (plan 19.4, T-057 N2). Do not edit by hand; regenerating")
    out.append("// changes the golden hash and is an intentional, recorded event.")
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace xdfix")
    out.append("{")
    out.append("")

    # Bank A: Dot, 64 x 48, ordinary scales in [0.001, 0.02].
    rows, scales = make_bank(rng, 64, 48,
                             lambda r, g: 0.001 + 0.019 * g.unit())
    out.append("// Bank A: Dot int8, 64 x 48, ordinary scales.")
    out.append("inline constexpr int32_t kBankACount = 64;")
    out.append("inline constexpr int32_t kBankADims = 48;")
    out.append(emit_i8("kBankARows", rows))
    out.append(emit_u32("kBankAScaleBits", [f32_bits(s) for s in scales]))
    out.append("")

    # Bank B: Cosine, 64 x 64, 4 channels of 16. Rows are raw int8 (the committed
    # payload is what the kernel dots; Cosine banks carry pre-normalized SOURCE
    # rows, but the fixture pins the quantized bytes directly). Scales normal.
    rows, scales = make_bank(rng, 64, 64,
                             lambda r, g: 0.005 + 0.01 * g.unit())
    out.append("// Bank B: Cosine int8, 64 x 64, four 16-element channels.")
    out.append("inline constexpr int32_t kBankBCount = 64;")
    out.append("inline constexpr int32_t kBankBDims = 64;")
    out.append("inline constexpr int32_t kBankBChannels = 4;")
    out.append(emit_i8("kBankBRows", rows))
    out.append(emit_u32("kBankBScaleBits", [f32_bits(s) for s in scales]))
    out.append("")

    # Bank C: L2, 48 x 32, ordinary scales.
    rows, scales = make_bank(rng, 48, 32,
                             lambda r, g: 0.002 + 0.015 * g.unit())
    out.append("// Bank C: L2 int8, 48 x 32, ordinary scales.")
    out.append("inline constexpr int32_t kBankCCount = 48;")
    out.append("inline constexpr int32_t kBankCDims = 32;")
    out.append(emit_i8("kBankCRows", rows))
    out.append(emit_u32("kBankCScaleBits", [f32_bits(s) for s in scales]))
    out.append("")

    # Bank D (adversarial, T-057 S1): Dot, 32 x 32. Row scales sweep 2^-88..2^-119,
    # including SUBNORMAL-float scales (exponent field 0). Against the tiny-scale
    # queries below, rowScale x queryScale x acc lands below, inside, and above the
    # float subnormal window - the exact territory where FTZ/DAZ divergence lives.
    rows = [[rng.i8() for _ in range(32)] for _ in range(32)]
    scale_bits = []
    for r in range(32):
        e = -88 - r  # 2^-88 .. 2^-119
        scale_bits.append(f32_bits(2.0 ** e))
    # Rows 28..31 get subnormal scales: 2^-127, 2^-130, 3 * 2^-140, 2^-149.
    scale_bits[28] = f32_bits(2.0 ** -127)
    scale_bits[29] = f32_bits(2.0 ** -130)
    scale_bits[30] = f32_bits(3.0 * 2.0 ** -140)
    scale_bits[31] = f32_bits(2.0 ** -149)
    out.append("// Bank D (adversarial): Dot int8, 32 x 32; scales sweep 2^-88..2^-119")
    out.append("// plus four subnormal-float scales - products straddle FLT_MIN.")
    out.append("inline constexpr int32_t kBankDCount = 32;")
    out.append("inline constexpr int32_t kBankDDims = 32;")
    out.append(emit_i8("kBankDRows", rows))
    out.append(emit_u32("kBankDScaleBits", scale_bits))
    out.append("")

    # Bank E (adversarial L2): 32 x 32, tiny scales 2^-60..2^-91 - the expanded
    # L2 epilogue's a/b/c terms and their cancellation run in tiny territory.
    rows = [[rng.i8() for _ in range(32)] for _ in range(32)]
    scale_bits = [f32_bits(2.0 ** (-60 - r)) for r in range(32)]
    out.append("// Bank E (adversarial): L2 int8, 32 x 32, scales 2^-60..2^-91.")
    out.append("inline constexpr int32_t kBankECount = 32;")
    out.append("inline constexpr int32_t kBankEDims = 32;")
    out.append(emit_i8("kBankERows", rows))
    out.append(emit_u32("kBankEScaleBits", scale_bits))
    out.append("")

    # Queries: float bits, 8 queries x 64 dims (sliced to each bank's dims; pad
    # lanes zeroed by the loader). Queries 0..4 ordinary [-1, 1]. Query 5 tiny
    # (maxAbs = 127 * 2^-40 -> queryScale 2^-40). Query 6 tinier (2^-52) with
    # SUBNORMAL elements mixed in (DAZ-proof decode exercised). Query 7 huge
    # (2^+30 range - large-magnitude epilogue).
    queries = []
    for q in range(5):
        queries.append([rng.unit() * 2.0 - 1.0 for _ in range(64)])
    tiny = [(rng.unit() * 2.0 - 1.0) * 127.0 * 2.0 ** -40 for _ in range(64)]
    tiny[0] = 127.0 * 2.0 ** -40  # pins maxAbs exactly
    queries.append(tiny)
    tinier = [(rng.unit() * 2.0 - 1.0) * 127.0 * 2.0 ** -52 for _ in range(64)]
    tinier[0] = 127.0 * 2.0 ** -52
    tinier[7] = 2.0 ** -130   # subnormal element
    tinier[9] = -(2.0 ** -140)  # subnormal element
    queries.append(tinier)
    queries.append([(rng.unit() * 2.0 - 1.0) * 2.0 ** 30 for _ in range(64)])
    out.append("// Queries: 8 x 64 float bits (sliced per bank; pads zeroed on load).")
    out.append("inline constexpr int32_t kQueryCount = 8;")
    out.append("inline constexpr int32_t kQueryDims = 64;")
    qbits = [f32_bits(struct.unpack("<f", struct.pack("<f", v))[0]) for row in queries for v in row]
    out.append(emit_u32("kQueryBits", qbits))
    out.append("")
    out.append("// Pinned cross-device hash over the full fixture battery (every entry")
    out.append("// point, every forced kernel path, every runner). Re-pinning is an")
    out.append("// intentional, recorded event. 0 means 'not yet pinned' (the test")
    out.append("// prints the computed value instead of asserting).")
    out.append(f"inline constexpr uint64_t kGoldenXdHash = 0x{golden:016x}ull;")
    out.append("")
    out.append("} // namespace xdfix")
    out.append("")

    with open("tests/xd_fixtures.h", "w", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote tests/xd_fixtures.h")


if __name__ == "__main__":
    main()
